// All inputs are explicitly SI unless the field label specifies mm, MPa or rpm.
const field = (key, label, unit, value, min = 0, strict = false) => ({
  key,
  label,
  unit,
  value,
  min,
  strict,
});
const positive = (key, label, unit, value) => field(key, label, unit, value, 0, true);
const signed = (key, label, unit, value) => field(key, label, unit, value, -1e15);
const c = (id, name, category, formula, unit, fields, compute, note, check) => ({
  id,
  name,
  category,
  formula,
  unit,
  fields,
  compute,
  note,
  check,
});
export const calculators = [
  c(
    'force',
    'Force',
    'Basics',
    'F = m × a',
    'N',
    [field('m', 'Mass', 'kg', 10), signed('a', 'Acceleration', 'm/s²', 9.81)],
    (v) => v.m * v.a,
    'Net force for constant mass. The sign indicates direction.',
  ),
  c(
    'torque',
    'Torque',
    'Basics',
    'T = F × r × sin θ',
    'N·m',
    [
      field('F', 'Force', 'N', 100),
      field('r', 'Lever arm', 'm', 0.5),
      field('theta', 'Angle between force and arm', '°', 90),
    ],
    (v) => v.F * v.r * Math.sin((v.theta * Math.PI) / 180),
    'Use the perpendicular lever arm. θ is the angle between the force and radius vector.',
    (v) => (v.theta > 180 ? 'Angle must be between 0° and 180°.' : null),
  ),
  c(
    'work',
    'Work',
    'Basics',
    'W = F × s × cos θ',
    'J',
    [
      field('F', 'Force', 'N', 100),
      field('s', 'Displacement', 'm', 2),
      field('theta', 'Angle to displacement', '°', 0),
    ],
    (v) => v.F * v.s * Math.cos((v.theta * Math.PI) / 180),
    'Constant force along a straight displacement.',
    (v) => (v.theta > 180 ? 'Angle must be between 0° and 180°.' : null),
  ),
  c(
    'power',
    'Power',
    'Basics',
    'P = W / t',
    'W',
    [signed('W', 'Work', 'J', 1000), positive('t', 'Time', 's', 5)],
    (v) => v.W / v.t,
    'Average power over the entered interval.',
  ),
  c(
    'pressure',
    'Pressure',
    'Basics',
    'p = F / A',
    'Pa',
    [field('F', 'Normal force', 'N', 1000), positive('A', 'Area', 'm²', 0.01)],
    (v) => v.F / v.A,
    'Uniform normal load divided by its loaded area.',
  ),
  c(
    'density',
    'Density',
    'Basics',
    'ρ = m / V',
    'kg/m³',
    [field('m', 'Mass', 'kg', 2.7), positive('V', 'Volume', 'm³', 0.001)],
    (v) => v.m / v.V,
    'Use the actual occupied volume, excluding external voids.',
  ),
  c(
    'velocity',
    'Velocity',
    'Basics',
    'v = Δx / Δt',
    'm/s',
    [signed('x', 'Displacement', 'm', 100), positive('t', 'Time', 's', 10)],
    (v) => v.x / v.t,
    'Average signed velocity; distance divided by time gives speed.',
  ),
  c(
    'acceleration',
    'Acceleration',
    'Basics',
    'a = (v − u) / t',
    'm/s²',
    [
      signed('v', 'Final velocity', 'm/s', 20),
      signed('u', 'Initial velocity', 'm/s', 0),
      positive('t', 'Elapsed time', 's', 5),
    ],
    (v) => (v.v - v.u) / v.t,
    'Average acceleration over the interval.',
  ),
  c(
    'kinetic-energy',
    'Kinetic Energy',
    'Basics',
    'KE = ½ m v²',
    'J',
    [field('m', 'Mass', 'kg', 10), signed('v', 'Velocity', 'm/s', 5)],
    (v) => 0.5 * v.m * v.v ** 2,
    'Translational energy; rotational energy is not included.',
  ),
  c(
    'potential-energy',
    'Potential Energy',
    'Basics',
    'PE = m g h',
    'J',
    [
      field('m', 'Mass', 'kg', 10),
      field('g', 'Gravity', 'm/s²', 9.81),
      signed('h', 'Height above datum', 'm', 2),
    ],
    (v) => v.m * v.g * v.h,
    'Gravitational energy relative to the chosen height datum.',
  ),
  c(
    'stress',
    'Stress',
    'Strength / Machine Design',
    'σ = F / A',
    'MPa',
    [signed('F', 'Axial force', 'N', 10000), positive('A', 'Cross-sectional area', 'mm²', 100)],
    (v) => v.F / v.A,
    'Nominal axial stress, without stress concentrations; N/mm² = MPa.',
  ),
  c(
    'strain',
    'Strain',
    'Strength / Machine Design',
    'ε = ΔL / L₀',
    'm/m',
    [signed('dL', 'Change in length', 'mm', 0.2), positive('L', 'Original length', 'mm', 100)],
    (v) => v.dL / v.L,
    'Engineering strain, dimensionless. Compression may be negative.',
  ),
  c(
    'youngs-modulus',
    'Young’s Modulus',
    'Strength / Machine Design',
    'E = σ / ε',
    'GPa',
    [positive('stress', 'Stress', 'MPa', 200), positive('strain', 'Strain', 'm/m', 0.001)],
    (v) => v.stress / v.strain / 1000,
    'Use stress and strain from the linear elastic region.',
  ),
  c(
    'factor-of-safety',
    'Factor of Safety',
    'Strength / Machine Design',
    'n = S / σ',
    '—',
    [
      positive('S', 'Limiting strength', 'MPa', 250),
      positive('stress', 'Working stress', 'MPa', 100),
    ],
    (v) => v.S / v.stress,
    'Choose yield, ultimate or fatigue strength appropriate to the failure mode.',
  ),
  c(
    'shaft-diameter',
    'Shaft Diameter',
    'Strength / Machine Design',
    'd = ∛(16 T / π τ)',
    'mm',
    [field('T', 'Torque', 'N·m', 200), positive('tau', 'Allowable shear stress', 'MPa', 50)],
    (v) => Math.cbrt((16 * v.T * 1000) / (Math.PI * v.tau)),
    'Solid circular shaft in pure torsion. Bending, keyways, fatigue and deflection need separate checks.',
  ),
  c(
    'shaft-power',
    'Shaft Power',
    'Strength / Machine Design',
    'P = 2π n T / 60',
    'kW',
    [field('n', 'Shaft speed', 'rpm', 1500), field('T', 'Torque', 'N·m', 100)],
    (v) => (2 * Math.PI * v.n * v.T) / 60000,
    'Steady rotational power; divide watts by 1000 for kW.',
  ),
  c(
    'gear-ratio',
    'Gear Ratio',
    'Strength / Machine Design',
    'i = Z₂ / Z₁',
    '—',
    [
      positive('z2', 'Driven gear teeth', 'teeth', 60),
      positive('z1', 'Driver gear teeth', 'teeth', 20),
    ],
    (v) => v.z2 / v.z1,
    'One external gear pair reverses rotation.',
    (v) =>
      !Number.isInteger(v.z1) || !Number.isInteger(v.z2)
        ? 'Tooth counts must be whole numbers.'
        : null,
  ),
  c(
    'gear-rpm',
    'Gear RPM',
    'Strength / Machine Design',
    'n₂ = n₁ Z₁ / Z₂',
    'rpm',
    [
      field('n', 'Input speed', 'rpm', 1500),
      positive('z1', 'Driver teeth', 'teeth', 20),
      positive('z2', 'Driven teeth', 'teeth', 60),
    ],
    (v) => (v.n * v.z1) / v.z2,
    'Ideal no-slip gear pair; output direction is opposite the input.',
    (v) =>
      !Number.isInteger(v.z1) || !Number.isInteger(v.z2)
        ? 'Tooth counts must be whole numbers.'
        : null,
  ),
  c(
    'gear-torque',
    'Gear Torque',
    'Strength / Machine Design',
    'T₂ = T₁ i η',
    'N·m',
    [
      field('T', 'Input torque', 'N·m', 100),
      positive('i', 'Gear ratio', '—', 3),
      field('eta', 'Efficiency', '%', 95),
    ],
    (v) => (v.T * v.i * v.eta) / 100,
    'Approximate transmitted torque including entered mechanical efficiency.',
    (v) => (v.eta > 100 ? 'Efficiency cannot exceed 100%.' : null),
  ),
  c(
    'spring',
    'Spring',
    'Strength / Machine Design',
    'F = k x',
    'N',
    [field('k', 'Spring stiffness', 'N/mm', 20), signed('x', 'Deflection', 'mm', 10)],
    (v) => v.k * v.x,
    'Hooke’s law for a linear spring within its elastic travel.',
  ),
  c(
    'bolt-stress',
    'Bolt Stress',
    'Strength / Machine Design',
    'σ = F / Aₜ',
    'MPa',
    [field('F', 'Tensile load', 'N', 10000), positive('A', 'Tensile stress area', 'mm²', 58)],
    (v) => v.F / v.A,
    'Enter the threaded tensile stress area, not the nominal shank area. Preload is a separate load.',
  ),
  c(
    'bearing-life',
    'Bearing Life',
    'Strength / Machine Design',
    'L₁₀h = (C/P)ᵖ × 10⁶ / (60 n)',
    'h',
    [
      positive('C', 'Dynamic load rating', 'N', 20000),
      positive('P', 'Equivalent dynamic load', 'N', 4000),
      positive('p', 'Life exponent', '—', 3),
      positive('n', 'Speed', 'rpm', 1500),
    ],
    (v) => ((v.C / v.P) ** v.p * 1e6) / (60 * v.n),
    'Basic rating life at 90% reliability. p = 3 for balls or 10/3 for rollers. Lubrication and contamination are not included.',
    (v) =>
      Math.abs(v.p - 3) > 1e-6 && Math.abs(v.p - 10 / 3) > 1e-5
        ? 'Use p = 3 for ball bearings or 3.333333333 for roller bearings.'
        : null,
  ),
  c(
    'ideal-gas',
    'Ideal Gas',
    'Thermodynamics',
    'p = n R T / V',
    'Pa',
    [
      field('n', 'Amount of gas', 'mol', 1),
      positive('T', 'Absolute temperature', 'K', 300),
      positive('V', 'Volume', 'm³', 0.025),
    ],
    (v) => (v.n * 8.314462618 * v.T) / v.V,
    'Uses R = 8.314462618 J/(mol·K). Ideal-gas approximation; absolute pressure.',
  ),
  c(
    'thermal-expansion',
    'Thermal Expansion',
    'Thermodynamics',
    'ΔL = α L₀ ΔT',
    'mm',
    [
      field('alpha', 'Linear expansion coefficient', '1/K', 0.000012),
      field('L', 'Original length', 'mm', 1000),
      signed('dT', 'Temperature change', 'K', 50),
    ],
    (v) => v.alpha * v.L * v.dT,
    'Unrestrained linear expansion with approximately constant α.',
  ),
  c(
    'thermal-efficiency',
    'Thermal Efficiency',
    'Thermodynamics',
    'η = Wnet / Qin × 100',
    '%',
    [field('W', 'Net work output', 'J', 350), positive('Q', 'Heat input', 'J', 1000)],
    (v) => (v.W / v.Q) * 100,
    'Heat-engine thermal efficiency.',
    (v) => (v.W > v.Q ? 'Net work cannot exceed heat input for this heat engine.' : null),
  ),
  c(
    'carnot-efficiency',
    'Carnot Efficiency',
    'Thermodynamics',
    'η = (1 − Tc / Th) × 100',
    '%',
    [positive('Tc', 'Cold reservoir', 'K', 300), positive('Th', 'Hot reservoir', 'K', 600)],
    (v) => (1 - v.Tc / v.Th) * 100,
    'Theoretical reversible upper bound. Both temperatures must be absolute kelvin.',
    (v) => (v.Tc >= v.Th ? 'Hot temperature must exceed cold temperature.' : null),
  ),
  c(
    'cop',
    'COP',
    'Thermodynamics',
    'COP = Quseful / Win',
    '—',
    [field('Q', 'Useful heating or cooling', 'J', 4000), positive('W', 'Work input', 'J', 1000)],
    (v) => v.Q / v.W,
    'Specify useful heating for heat pumps or useful cooling for refrigerators. COP may exceed 1.',
  ),
  c(
    'reynolds',
    'Reynolds Number',
    'Fluid Mechanics',
    'Re = ρ v D / μ',
    '—',
    [
      positive('rho', 'Density', 'kg/m³', 998),
      field('v', 'Mean speed', 'm/s', 1),
      positive('D', 'Hydraulic diameter', 'm', 0.05),
      positive('mu', 'Dynamic viscosity', 'Pa·s', 0.001),
    ],
    (v) => (v.rho * v.v * v.D) / v.mu,
    'For round pipes: typically laminar below 2300, transitional 2300–4000, turbulent above 4000.',
  ),
  c(
    'bernoulli',
    'Bernoulli Equation',
    'Fluid Mechanics',
    'p₂ = p₁ + ½ρ(v₁² − v₂²) + ρg(z₁ − z₂)',
    'Pa',
    [
      signed('p', 'Pressure at point 1', 'Pa', 200000),
      positive('rho', 'Density', 'kg/m³', 998),
      field('v1', 'Velocity at point 1', 'm/s', 1),
      field('v2', 'Velocity at point 2', 'm/s', 3),
      signed('z1', 'Elevation at point 1', 'm', 0),
      signed('z2', 'Elevation at point 2', 'm', 2),
    ],
    (v) => v.p + 0.5 * v.rho * (v.v1 ** 2 - v.v2 ** 2) + v.rho * 9.81 * (v.z1 - v.z2),
    'Steady incompressible inviscid flow along a streamline; no pump, turbine or friction losses.',
  ),
  c(
    'flow-rate',
    'Flow Rate',
    'Fluid Mechanics',
    'Q = A v',
    'm³/s',
    [field('A', 'Flow area', 'm²', 0.002), field('v', 'Mean speed', 'm/s', 2)],
    (v) => v.A * v.v,
    'Volumetric flow through a section at mean speed.',
  ),
  c(
    'pipe-velocity',
    'Pipe Velocity',
    'Fluid Mechanics',
    'v = 4Q / (πD²)',
    'm/s',
    [field('Q', 'Volumetric flow', 'm³/s', 0.01), positive('D', 'Inside diameter', 'm', 0.1)],
    (v) => (4 * v.Q) / (Math.PI * v.D ** 2),
    'Full circular pipe; use internal diameter.',
  ),
  c(
    'head-loss',
    'Head Loss',
    'Fluid Mechanics',
    'hf = f (L/D) v² / (2g)',
    'm',
    [
      field('f', 'Darcy friction factor', '—', 0.02),
      field('L', 'Pipe length', 'm', 20),
      positive('D', 'Inside diameter', 'm', 0.1),
      field('v', 'Mean speed', 'm/s', 2),
    ],
    (v) => (((v.f * v.L) / v.D) * v.v ** 2) / (2 * 9.81),
    'Darcy–Weisbach major loss. Darcy factor is four times the Fanning factor. Fittings are excluded.',
  ),
  c(
    'hydraulic-power',
    'Hydraulic Power',
    'Fluid Mechanics',
    'P = Δp Q',
    'kW',
    [field('p', 'Pressure rise', 'Pa', 200000), field('Q', 'Flow rate', 'm³/s', 0.01)],
    (v) => (v.p * v.Q) / 1000,
    'Ideal hydraulic output at the entered pressure rise and flow.',
  ),
  c(
    'pump-power',
    'Pump Power',
    'Fluid Mechanics',
    'Pshaft = ρ g Q H / η',
    'kW',
    [
      positive('rho', 'Density', 'kg/m³', 998),
      field('Q', 'Flow', 'm³/s', 0.01),
      field('H', 'Total head', 'm', 20),
      positive('eta', 'Pump efficiency', '%', 75),
    ],
    (v) => (v.rho * 9.81 * v.Q * v.H) / (v.eta / 100) / 1000,
    'Shaft input power. Motor efficiency and service margins are additional considerations.',
    (v) => (v.eta > 100 ? 'Efficiency cannot exceed 100%.' : null),
  ),
  c(
    'cutting-speed',
    'Cutting Speed',
    'Manufacturing',
    'Vc = π D n / 1000',
    'm/min',
    [field('D', 'Cutting diameter', 'mm', 50), field('n', 'Spindle speed', 'rpm', 1000)],
    (v) => (Math.PI * v.D * v.n) / 1000,
    'Peripheral cutting speed for turning or a rotating cutter.',
  ),
  c(
    'rpm',
    'RPM',
    'Manufacturing',
    'n = 1000 Vc / (πD)',
    'rpm',
    [field('Vc', 'Cutting speed', 'm/min', 150), positive('D', 'Cutting diameter', 'mm', 50)],
    (v) => (1000 * v.Vc) / (Math.PI * v.D),
    'Consult tool-maker cutting data and machine speed limits.',
  ),
  c(
    'feed-rate',
    'Feed Rate',
    'Manufacturing',
    'vf = fz z n',
    'mm/min',
    [
      field('fz', 'Feed per tooth', 'mm/tooth', 0.05),
      positive('z', 'Number of teeth', 'teeth', 4),
      field('n', 'Spindle speed', 'rpm', 1500),
    ],
    (v) => v.fz * v.z * v.n,
    'Milling table feed; z is the number of effective cutting teeth.',
    (v) => (!Number.isInteger(v.z) ? 'Number of teeth must be a whole number.' : null),
  ),
  c(
    'machining-time',
    'Machining Time',
    'Manufacturing',
    't = L / vf',
    'min',
    [field('L', 'Total tool travel', 'mm', 150), positive('vf', 'Feed rate', 'mm/min', 300)],
    (v) => v.L / v.vf,
    'One cutting pass. Include approach and overtravel in L; setup and tool changes are excluded.',
  ),
  c(
    'mrr',
    'Material Removal Rate',
    'Manufacturing',
    'MRR = ap ae vf',
    'mm³/min',
    [
      field('ap', 'Axial depth', 'mm', 2),
      field('ae', 'Radial width', 'mm', 10),
      field('vf', 'Feed rate', 'mm/min', 300),
    ],
    (v) => v.ap * v.ae * v.vf,
    'Rectangular milling engagement approximation; use consistent millimetre units.',
  ),
  c(
    'second-moment-rect',
    'Second Moment of Area (Rectangle)',
    'Structures & Heat Transfer',
    'I = b h³ / 12',
    'mm⁴',
    [positive('b', 'Section width', 'mm', 50), positive('h', 'Section height (bending direction)', 'mm', 100)],
    (v) => (v.b * v.h ** 3) / 12,
    'Rectangular section bending about the centroidal axis parallel to the width b.',
  ),
  c(
    'bending-stress',
    'Bending Stress',
    'Structures & Heat Transfer',
    'σ = M c / I',
    'MPa',
    [
      positive('M', 'Bending moment', 'N·m', 500),
      positive('c', 'Distance to outer fibre', 'mm', 25),
      positive('I', 'Second moment of area', 'mm⁴', 800000),
    ],
    (v) => (v.M * 1000 * v.c) / v.I,
    'Elastic flexure formula. Moment is converted from N·m to N·mm so that the result is in MPa.',
  ),
  c(
    'beam-ss-deflection',
    'Simply Supported Beam Deflection',
    'Structures & Heat Transfer',
    'δ = F L³ / (48 E I)',
    'mm',
    [
      positive('F', 'Central point load', 'N', 1000),
      positive('L', 'Span', 'mm', 1000),
      positive('E', "Young's modulus", 'MPa', 200000),
      positive('I', 'Second moment of area', 'mm⁴', 800000),
    ],
    (v) => (v.F * v.L ** 3) / (48 * v.E * v.I),
    'Maximum mid-span deflection of a prismatic beam, linear elastic, small deflections, load at mid-span.',
  ),
  c(
    'cantilever-deflection',
    'Cantilever Beam Deflection',
    'Structures & Heat Transfer',
    'δ = F L³ / (3 E I)',
    'mm',
    [
      positive('F', 'Tip load', 'N', 1000),
      positive('L', 'Length', 'mm', 1000),
      positive('E', "Young's modulus", 'MPa', 200000),
      positive('I', 'Second moment of area', 'mm⁴', 800000),
    ],
    (v) => (v.F * v.L ** 3) / (3 * v.E * v.I),
    'Tip deflection of a prismatic cantilever with a point load at the free end.',
  ),
  c(
    'euler-buckling',
    'Euler Buckling Load',
    'Structures & Heat Transfer',
    'Pcr = π² E I / (K L)²',
    'N',
    [
      positive('E', "Young's modulus", 'MPa', 200000),
      positive('I', 'Minimum second moment of area', 'mm⁴', 800000),
      positive('K', 'Effective length factor', '–', 1),
      positive('L', 'Column length', 'mm', 2000),
    ],
    (v) => (Math.PI ** 2 * v.E * v.I) / (v.K * v.L) ** 2,
    'Elastic buckling of a slender column. K = 1 pinned–pinned, 0.5 fixed–fixed, 2 fixed–free. Check slenderness before use.',
  ),
  c(
    'torsional-shear',
    'Torsional Shear Stress (Solid Shaft)',
    'Structures & Heat Transfer',
    'τ = 16 T / (π d³)',
    'MPa',
    [positive('T', 'Torque', 'N·m', 200), positive('d', 'Shaft diameter', 'mm', 40)],
    (v) => (16 * v.T * 1000) / (Math.PI * v.d ** 3),
    'Maximum surface shear stress of a solid circular shaft in pure torsion.',
  ),
  c(
    'hoop-stress',
    'Thin-Wall Vessel Hoop Stress',
    'Structures & Heat Transfer',
    'σh = p d / (2 t)',
    'MPa',
    [
      positive('p', 'Internal gauge pressure', 'MPa', 2),
      positive('d', 'Inside diameter', 'mm', 500),
      positive('t', 'Wall thickness', 'mm', 5),
    ],
    (v) => (v.p * v.d) / (2 * v.t),
    'Valid when wall thickness is small compared with diameter (d/t > 20). Longitudinal stress is half this value.',
  ),
  c(
    'flywheel-energy',
    'Flywheel Kinetic Energy',
    'Structures & Heat Transfer',
    'E = ½ I ω²,  ω = 2πn / 60',
    'J',
    [positive('I', 'Moment of inertia', 'kg·m²', 5), positive('n', 'Speed', 'rpm', 1500)],
    (v) => 0.5 * v.I * ((2 * Math.PI * v.n) / 60) ** 2,
    'Stored rotational energy. Check rim speed and material burst limits for real flywheels.',
  ),
  c(
    'belt-length',
    'Open Belt Length',
    'Structures & Heat Transfer',
    'L ≈ 2C + π(D + d)/2 + (D − d)² / 4C',
    'mm',
    [
      positive('C', 'Centre distance', 'mm', 500),
      positive('D', 'Large pulley diameter', 'mm', 200),
      positive('d', 'Small pulley diameter', 'mm', 100),
    ],
    (v) => 2 * v.C + (Math.PI * (v.D + v.d)) / 2 + (v.D - v.d) ** 2 / (4 * v.C),
    'Standard open-belt approximation. Select the nearest standard belt length afterwards.',
    (v) => (v.D < v.d ? 'Large pulley diameter D must be at least the small pulley diameter d.' : null),
  ),
  c(
    'conduction',
    'Heat Conduction (Fourier)',
    'Structures & Heat Transfer',
    'Q = k A ΔT / L',
    'W',
    [
      positive('k', 'Thermal conductivity', 'W/(m·K)', 50),
      positive('A', 'Area', 'm²', 0.5),
      positive('dT', 'Temperature difference', 'K', 80),
      positive('L', 'Thickness', 'm', 0.1),
    ],
    (v) => (v.k * v.A * v.dT) / v.L,
    'Steady one-dimensional conduction through a plane wall.',
  ),
  c(
    'convection',
    'Convection Heat Transfer',
    'Structures & Heat Transfer',
    'Q = h A ΔT',
    'W',
    [
      positive('h', 'Convection coefficient', 'W/(m²·K)', 25),
      positive('A', 'Surface area', 'm²', 2),
      positive('dT', 'Surface-to-fluid temperature difference', 'K', 40),
    ],
    (v) => v.h * v.A * v.dT,
    "Newton's law of cooling. h depends strongly on geometry, fluid and flow regime.",
  ),
  c(
    'radiation',
    'Radiation Heat Transfer',
    'Structures & Heat Transfer',
    'Q = ε σ A (Th⁴ − Tc⁴)',
    'W',
    [
      positive('eps', 'Emissivity', '–', 0.8),
      positive('A', 'Surface area', 'm²', 1),
      positive('Th', 'Hot surface temperature (absolute)', 'K', 500),
      positive('Tc', 'Surroundings temperature (absolute)', 'K', 300),
    ],
    (v) => v.eps * 5.670374419e-8 * v.A * (v.Th ** 4 - v.Tc ** 4),
    'Grey surface exchanging radiation with large surroundings. Temperatures must be in kelvin.',
    (v) => (v.eps > 1 ? 'Emissivity must be between 0 and 1.' : null),
  ),
  c(
    'lmtd',
    'Log-Mean Temperature Difference',
    'Structures & Heat Transfer',
    'LMTD = (ΔT₁ − ΔT₂) / ln(ΔT₁ / ΔT₂)',
    'K',
    [positive('a', 'Terminal difference ΔT₁', 'K', 80), positive('b', 'Terminal difference ΔT₂', 'K', 40)],
    (v) => (Math.abs(v.a - v.b) < 1e-12 ? v.a : (v.a - v.b) / Math.log(v.a / v.b)),
    'Heat-exchanger driving temperature. Use with Q = U A LMTD for counter-flow or parallel flow.',
  ),
];
export function evaluate(calc, raw) {
  const values = {};
  for (const f of calc.fields) {
    if (raw[f.key] === undefined || String(raw[f.key]).trim() === '')
      throw new Error(`Enter ${f.label.toLowerCase()}.`);
    const n = Number(raw[f.key]);
    if (!Number.isFinite(n) || Math.abs(n) > 1e15)
      throw new Error(`${f.label} must be a finite number with magnitude ≤ 10¹⁵.`);
    if (n < f.min || (f.strict && n === f.min))
      throw new Error(`${f.label} must be ${f.strict ? 'greater than' : 'at least'} ${f.min}.`);
    values[f.key] = n;
  }
  const error = calc.check?.(values);
  if (error) throw new Error(error);
  const result = calc.compute(values);
  if (!Number.isFinite(result) || Math.abs(result) > 1e30)
    throw new Error('Result is outside the supported range. Check your units and inputs.');
  return { result, values };
}
export const formatNumber = (n) =>
  new Intl.NumberFormat('en-US', { maximumSignificantDigits: 7 }).format(n);
