import { formatNumber } from './registry.js';
// Explicit substitutions make scaling and constants inspectable to learners.
const expressions = {
  force: (v) => `${v.m} × ${v.a}`,
  torque: (v) => `${v.F} × ${v.r} × sin(${v.theta}°)`,
  work: (v) => `${v.F} × ${v.s} × cos(${v.theta}°)`,
  power: (v) => `${v.W} ÷ ${v.t}`,
  pressure: (v) => `${v.F} ÷ ${v.A}`,
  density: (v) => `${v.m} ÷ ${v.V}`,
  velocity: (v) => `${v.x} ÷ ${v.t}`,
  acceleration: (v) => `(${v.v} − ${v.u}) ÷ ${v.t}`,
  'kinetic-energy': (v) => `0.5 × ${v.m} × ${v.v}²`,
  'potential-energy': (v) => `${v.m} × ${v.g} × ${v.h}`,
  stress: (v) => `${v.F} ÷ ${v.A}`,
  strain: (v) => `${v.dL} ÷ ${v.L}`,
  'youngs-modulus': (v) => `(${v.stress} ÷ ${v.strain}) ÷ 1000`,
  'factor-of-safety': (v) => `${v.S} ÷ ${v.stress}`,
  'shaft-diameter': (v) => `∛(16 × ${v.T} × 1000 ÷ (π × ${v.tau}))`,
  'shaft-power': (v) => `2π × ${v.n} × ${v.T} ÷ 60000`,
  'gear-ratio': (v) => `${v.z2} ÷ ${v.z1}`,
  'gear-rpm': (v) => `${v.n} × ${v.z1} ÷ ${v.z2}`,
  'gear-torque': (v) => `${v.T} × ${v.i} × (${v.eta} ÷ 100)`,
  spring: (v) => `${v.k} × ${v.x}`,
  'bolt-stress': (v) => `${v.F} ÷ ${v.A}`,
  'bearing-life': (v) => `(${v.C} ÷ ${v.P})^${v.p} × 10⁶ ÷ (60 × ${v.n})`,
  'ideal-gas': (v) => `${v.n} × 8.314462618 × ${v.T} ÷ ${v.V}`,
  'thermal-expansion': (v) => `${v.alpha} × ${v.L} × ${v.dT}`,
  'thermal-efficiency': (v) => `${v.W} ÷ ${v.Q} × 100`,
  'carnot-efficiency': (v) => `(1 − ${v.Tc} ÷ ${v.Th}) × 100`,
  cop: (v) => `${v.Q} ÷ ${v.W}`,
  reynolds: (v) => `${v.rho} × ${v.v} × ${v.D} ÷ ${v.mu}`,
  bernoulli: (v) =>
    `${v.p} + 0.5 × ${v.rho} × (${v.v1}² − ${v.v2}²) + ${v.rho} × 9.81 × (${v.z1} − ${v.z2})`,
  'flow-rate': (v) => `${v.A} × ${v.v}`,
  'pipe-velocity': (v) => `4 × ${v.Q} ÷ (π × ${v.D}²)`,
  'head-loss': (v) => `${v.f} × (${v.L} ÷ ${v.D}) × ${v.v}² ÷ (2 × 9.81)`,
  'hydraulic-power': (v) => `${v.p} × ${v.Q} ÷ 1000`,
  'pump-power': (v) => `${v.rho} × 9.81 × ${v.Q} × ${v.H} ÷ (${v.eta} ÷ 100) ÷ 1000`,
  'cutting-speed': (v) => `π × ${v.D} × ${v.n} ÷ 1000`,
  rpm: (v) => `1000 × ${v.Vc} ÷ (π × ${v.D})`,
  'feed-rate': (v) => `${v.fz} × ${v.z} × ${v.n}`,
  'machining-time': (v) => `${v.L} ÷ ${v.vf}`,
  mrr: (v) => `${v.ap} × ${v.ae} × ${v.vf}`,
  'second-moment-rect': (v) => `${v.b} × ${v.h}³ ÷ 12`,
  'bending-stress': (v) => `${v.M} × 1000 × ${v.c} ÷ ${v.I}`,
  'beam-ss-deflection': (v) => `${v.F} × ${v.L}³ ÷ (48 × ${v.E} × ${v.I})`,
  'cantilever-deflection': (v) => `${v.F} × ${v.L}³ ÷ (3 × ${v.E} × ${v.I})`,
  'euler-buckling': (v) => `π² × ${v.E} × ${v.I} ÷ (${v.K} × ${v.L})²`,
  'torsional-shear': (v) => `16 × ${v.T} × 1000 ÷ (π × ${v.d}³)`,
  'hoop-stress': (v) => `${v.p} × ${v.d} ÷ (2 × ${v.t})`,
  'flywheel-energy': (v) => `0.5 × ${v.I} × (2π × ${v.n} ÷ 60)²`,
  'belt-length': (v) => `2 × ${v.C} + π × (${v.D} + ${v.d}) ÷ 2 + (${v.D} − ${v.d})² ÷ (4 × ${v.C})`,
  conduction: (v) => `${v.k} × ${v.A} × ${v.dT} ÷ ${v.L}`,
  convection: (v) => `${v.h} × ${v.A} × ${v.dT}`,
  radiation: (v) => `${v.eps} × 5.670374419×10⁻⁸ × ${v.A} × (${v.Th}⁴ − ${v.Tc}⁴)`,
  lmtd: (v) => `(${v.a} − ${v.b}) ÷ ln(${v.a} ÷ ${v.b})`,
};
const scaling = {
  'bending-stress': 'Convert moment from N·m to N·mm (×1000); N/mm² equals MPa.',
  'torsional-shear': 'Convert torque from N·m to N·mm (×1000); N/mm² equals MPa.',
  radiation: 'Use absolute temperatures and the Stefan–Boltzmann constant 5.670374419×10⁻⁸ W/(m²·K⁴).',
  'flywheel-energy': 'Convert rpm to rad/s by multiplying by 2π/60.',
  'shaft-diameter': 'Convert torque from N·m to N·mm by multiplying by 1000; MPa equals N/mm².',
  'shaft-power':
    'Divide rpm by 60 to obtain revolutions per second, and watts by 1000 to obtain kW.',
  'youngs-modulus': 'Divide MPa by dimensionless strain, then divide by 1000 to obtain GPa.',
  'ideal-gas': 'Use universal R = 8.314462618 J/(mol·K) and absolute kelvin.',
  'pump-power':
    'Convert percentage efficiency to a fraction. Use g = 9.81 m/s². Convert watts to kW.',
  'gear-torque': 'Divide the entered percentage efficiency by 100.',
  bernoulli: 'Use g = 9.81 m/s². Every term in this pressure form is in pascals.',
  'head-loss': 'Use g = 9.81 m/s² and the Darcy friction factor.',
  'hydraulic-power': 'ΔpQ gives watts; divide by 1000 for kilowatts.',
  'cutting-speed': 'Divide by 1000 to convert the diameter contribution from mm to m.',
  rpm: 'Multiply cutting speed by 1000 to convert m/min to mm/min.',
};
export function calculationSteps(calc, answer) {
  return [
    `Identify the inputs: ${calc.fields.map((f) => `${f.key} = ${formatNumber(answer.values[f.key])} ${f.unit}`).join('; ')}.`,
    scaling[calc.id] || `Keep the stated units consistent. Apply ${calc.formula}.`,
    `Substitute: ${expressions[calc.id](answer.values)}.`,
    `Evaluate: ${formatNumber(answer.result)} ${calc.unit}.`,
  ];
}
